export const MT5_CONFIG = {
  baseUrl: "http://173.208.156.141:6701",
  swaggerUrl: "http://173.208.156.141:6700/swagger/v1/swagger.json",
  credentials: {
    mngId: 1146,
    pwd: "@tCnE8Sc",
    srvIp: "86.104.251.148:443",
  },
  endpoints: {
    token: "/Home/token",
    login: "/Home/login",
    logout: "/Home/logout",
    getPosition: "/Home/getPosition",
    getPositionByGroup: "/Home/getPositionbyGroup",
    getPositionBySymbol: "/Home/getPositionBySymbol",
    getSymbolInfo: "/Home/getSymbolInfo",
    journal: "/Home/journal",
    tradeHistory: "/Home/tradehistory",
    getHistoryFromDBTime: "/Home/getHistoryFromDBTime",
    tradeHistoryByLoginTime: "/Home/tradehistoryByLoginTime",
    getLogs: "/Home/getLogs",
    createAccount: "/Home/createAccount",
    getUserInfo: "/Home/getUserInfo",
    getAllUsers: "/Home/getAllUsers",
    getAllAccountInfos: "/Home/getAllAccountInfos",
    updateAccount: "/Home/updateAccount",
    updatePwd: "/Home/updatePwd",
    checkPwd: "/Home/checkPwd",
    userDisable: "/Home/userDisable",
    tradeDisable: "/Home/tradeDisable",
    balanceOP: "/Home/balanceOP",
    transfer: "/Home/transfer",
    sendOpenTrade: "/Home/sendOpenTrade",
    sendCloseTrade: "/Home/sendCloseTrade",
    sendCloseByTrade: "/Home/sendCloseByTrade",
    pendingOrder: "/Home/pendingOrder",
    updatePosition: "/Home/updatePostion",
    orderCancel: "/Home/OrderCancel",
    orderUpdate: "/Home/orderUpdate",
    getChart: "/Home/getchart",
  },
}
